"""Add bot_username to Tenant

Revision ID: 8e1962ce73d8
Revises: a1b84ef63f1e
Create Date: 2025-12-02 22:31:58.372834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1962ce73d8'
down_revision: Union[str, None] = 'a1b84ef63f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('bot_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'bot_username')
    # ### end Alembic commands ###
