"""Add full tenant details

Revision ID: 9c8a5d218b59
Revises: 7054e5c02af1
Create Date: 2025-12-01 01:50:58.322765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a5d218b59'
down_revision: Union[str, None] = '7054e5c02af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('custom_domain', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('active_until', sa.Date(), nullable=True))
    op.add_column('tenant', sa.Column('branch_limit', sa.Integer(), nullable=True))
    op.add_column('tenant', sa.Column('owner_phone_contact', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tenant', ['custom_domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_column('tenant', 'owner_phone_contact')
    op.drop_column('tenant', 'branch_limit')
    op.drop_column('tenant', 'active_until')
    op.drop_column('tenant', 'telegram_bot_token')
    op.drop_column('tenant', 'custom_domain')
    # ### end Alembic commands ###
