"""Add Client and Order updates

Revision ID: a1b84ef63f1e
Revises: fd6cc8903888
Create Date: 2025-12-02 22:16:07.269962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b84ef63f1e'
down_revision: Union[str, None] = 'fd6cc8903888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('payment_proof', sa.String(), nullable=True))
    op.add_column('order', sa.Column('source', sa.String(), nullable=True))
    op.create_foreign_key(None, 'order', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'source')
    op.drop_column('order', 'payment_proof')
    op.drop_column('order', 'is_paid')
    op.drop_column('order', 'client_id')
    # ### end Alembic commands ###
